# Generated by Django 4.1.4 on 2023-01-10 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('symbol', models.CharField(max_length=16)),
                ('price_change_24h', models.FloatField(blank=True, null=True)),
                ('market_cap', models.FloatField(blank=True, null=True)),
                ('volume_24h', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('group', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='TradingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_coin_symbol', models.CharField(max_length=16)),
                ('price', models.FloatField()),
                ('bid', models.FloatField()),
                ('ask', models.FloatField()),
                ('volume', models.FloatField()),
                ('trade_url', models.URLField()),
                ('base_coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage_pairs.coin')),
                ('exchange', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arbitrage_pairs.exchange')),
            ],
        ),
        migrations.CreateModel(
            name='ArbitragePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spread', models.FloatField()),
                ('base_trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='base_arbitrage_pairs', to='arbitrage_pairs.tradingpair')),
                ('target_trading_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_arbitrage_pairs', to='arbitrage_pairs.tradingpair')),
            ],
        ),
    ]
